import "package:flutter/foundation.dart" show defaultTargetPlatform, TargetPlatform;
import "package:flutter/material.dart";
import "package:mobile_nebula/components/pill_chip.dart";
import "package:mobile_nebula/components/pill_segmented_button.dart";

// Originally generated by https://material-foundation.github.io/material-theme-builder/
// from a source color of #5D23DD

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      //TODO: Make sure you also update dark mode colors that you changed in light
      primary: Color.fromRGBO(93, 34, 221, 1),
      surfaceTint: Color(4284700303),
      onPrimary: Color.fromRGBO(255, 255, 255, 1),
      primaryContainer: Color.fromRGBO(255, 255, 255, 1),
      onPrimaryContainer: Color(4283121270),
      secondary: Color(4284570481),
      onSecondary: Color(4294967295),
      secondaryContainer: Color.fromRGBO(240, 242, 244, 1),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4286403169),
      onTertiary: Color(4294967295),
      tertiaryContainer: Color.fromRGBO(240, 234, 252, 1),
      onTertiaryContainer: Color.fromRGBO(93, 34, 221, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4294957782),
      onErrorContainer: Color(4287823882),
      surface: Color.fromRGBO(226, 229, 233, 1),
      onSurface: Colors.black,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4286150015),
      outlineVariant: Color.fromRGBO(226, 229, 233, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4281478965),
      inversePrimary: Color(4291673599),
      primaryFixed: Color(4293451519),
      onPrimaryFixed: Color(4280225864),
      primaryFixedDim: Color(4291673599),
      onPrimaryFixedVariant: Color(4283121270),
      secondaryFixed: Color(4293385976),
      onSecondaryFixed: Color(4280097067),
      secondaryFixedDim: Color(4291544028),
      onSecondaryFixedVariant: Color(4282991704),
      tertiaryFixed: Color(4294957540),
      onTertiaryFixed: Color(4281405726),
      tertiaryFixedDim: Color(4293834953),
      onTertiaryFixedVariant: Color(4284693322),
      surfaceDim: Color(4292729056),
      surfaceBright: Color(4294834175),
      surfaceContainerLowest: Color(4294967295),
      surfaceContainerLow: Color(4294439674),
      surfaceContainer: Color(4294110452),
      surfaceContainerHigh: Color(4293715694),
      surfaceContainerHighest: Color.fromRGBO(226, 229, 233, 1),
    );
  }

  ThemeData light() {
    return theme(
      lightScheme(),
      BadgeThemeData(backgroundColor: Color(0xfff0eafc), textColor: Color(0xff4b1bb1)),
      appColors: const AppColors(primaryMuted: Color(0xFFBEA7F1)),
      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(4282002788),
      surfaceTint: Color(4284700303),
      onPrimary: Color(4294967295),
      primaryContainer: Color.fromRGBO(255, 255, 255, 1),
      onPrimaryContainer: Color(4294967295),
      secondary: Color(4281873223),
      onSecondary: Color(4294967295),
      secondaryContainer: Color(4285557376),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4283444025),
      onTertiary: Color(4294967295),
      tertiaryContainer: Color.fromRGBO(240, 234, 252, 1),
      onTertiaryContainer: Color.fromRGBO(93, 34, 221, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4291767335),
      onErrorContainer: Color(4294967295),
      surface: Color.fromRGBO(226, 229, 233, 1),
      onSurface: Colors.black,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4283715930),
      outlineVariant: Color.fromRGBO(226, 229, 233, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4281478965),
      inversePrimary: Color(4291673599),
      primaryFixed: Color(4285686943),
      onPrimaryFixed: Color(4294967295),
      primaryFixedDim: Color(4284042373),
      onPrimaryFixedVariant: Color(4294967295),
      secondaryFixed: Color(4285557376),
      onSecondaryFixed: Color(4294967295),
      secondaryFixedDim: Color(4283912807),
      onSecondaryFixedVariant: Color(4294967295),
      tertiaryFixed: Color(4287455344),
      onTertiaryFixed: Color(4294967295),
      tertiaryFixedDim: Color(4285679960),
      onTertiaryFixedVariant: Color(4294967295),
      surfaceDim: Color(4291478989),
      surfaceBright: Color(4294834175),
      surfaceContainerLowest: Color(4294967295),
      surfaceContainerLow: Color(4294439674),
      surfaceContainer: Color(4293715694),
      surfaceContainerHigh: Color(4292926435),
      surfaceContainerHighest: Color.fromRGBO(226, 229, 233, 1),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(
      lightMediumContrastScheme(),
      BadgeThemeData(backgroundColor: Color(0xfff0eafc), textColor: Color(0xff4b1bb1)),
      appColors: const AppColors(primaryMuted: Color(0xFFBEA7F1)),
      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(4281344857),
      surfaceTint: Color(4284700303),
      onPrimary: Color(4294967295),
      primaryContainer: Color.fromRGBO(255, 255, 255, 1),
      onPrimaryContainer: Color(4294967295),
      secondary: Color(4281215292),
      onSecondary: Color(4294967295),
      secondaryContainer: Color(4283123291),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4282655023),
      onTertiary: Color(4294967295),
      tertiaryContainer: Color.fromRGBO(240, 234, 252, 1),
      onTertiaryContainer: Color.fromRGBO(93, 34, 221, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4288151562),
      onErrorContainer: Color(4294967295),
      surface: Color.fromRGBO(226, 229, 233, 1),
      onSurface: Colors.black,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4281150259),
      outlineVariant: Color.fromRGBO(226, 229, 233, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4281478965),
      inversePrimary: Color(4291673599),
      primaryFixed: Color(4283252856),
      onPrimaryFixed: Color(4294967295),
      primaryFixedDim: Color(4281739616),
      onPrimaryFixedVariant: Color(4294967295),
      secondaryFixed: Color(4283123291),
      onSecondaryFixed: Color(4294967295),
      secondaryFixedDim: Color(4281675843),
      onSecondaryFixedVariant: Color(4294967295),
      tertiaryFixed: Color(4284824908),
      onTertiaryFixed: Color(4294967295),
      tertiaryFixedDim: Color(4283180853),
      onTertiaryFixedVariant: Color(4294967295),
      surfaceDim: Color(4290557887),
      surfaceBright: Color(4294834175),
      surfaceContainerLowest: Color(4294967295),
      surfaceContainerLow: Color(4294242295),
      surfaceContainer: Color(4293321193),
      surfaceContainerHigh: Color(4292400090),
      surfaceContainerHighest: Color.fromRGBO(226, 229, 233, 1),
    );
  }

  ThemeData lightHighContrast() {
    return theme(
      lightHighContrastScheme(),
      BadgeThemeData(backgroundColor: Color(0xfff0eafc), textColor: Color(0xff4b1bb1)),
      appColors: const AppColors(primaryMuted: Color(0xFFBEA7F1)),
      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromRGBO(126, 79, 227, 1),
      surfaceTint: Color(4291673599),
      onPrimary: Color.fromRGBO(255, 255, 255, 1),
      primaryContainer: Color.fromRGBO(43, 50, 59, 1),
      onPrimaryContainer: Color(4293451519),
      secondary: Color(4291544028),
      onSecondary: Color(4281478721),
      secondaryContainer: Color(4282991704),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4293834953),
      onTertiary: Color(4282983731),
      tertiaryContainer: Color.fromRGBO(158, 123, 234, 0.16),
      onTertiaryContainer: Color.fromRGBO(158, 123, 234, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4287823882),
      onErrorContainer: Color(4294957782),
      surface: Color.fromRGBO(22, 25, 29, 1),
      onSurface: Colors.white,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4287860633),
      outlineVariant: Color.fromRGBO(65, 75, 88, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4293321193),
      inversePrimary: Color(4284700303),
      primaryFixed: Color(4293451519),
      onPrimaryFixed: Color(4280225864),
      primaryFixedDim: Color(4291673599),
      onPrimaryFixedVariant: Color(4283121270),
      secondaryFixed: Color(4293385976),
      onSecondaryFixed: Color(4280097067),
      secondaryFixedDim: Color(4291544028),
      onSecondaryFixedVariant: Color(4282991704),
      tertiaryFixed: Color(4294957540),
      onTertiaryFixed: Color(4281405726),
      tertiaryFixedDim: Color(4293834953),
      onTertiaryFixedVariant: Color(4284693322),
      surfaceDim: Color(4279505688),
      surfaceBright: Color(4282005566),
      surfaceContainerLowest: Color(4279176467),
      surfaceContainerLow: Color(4280032032),
      surfaceContainer: Color(4280295204),
      surfaceContainerHigh: Color(4281018671),
      surfaceContainerHighest: Color.fromRGBO(65, 75, 88, 1),
    );
  }

  ThemeData dark() {
    return theme(
      darkScheme(),
      BadgeThemeData(backgroundColor: Color.fromRGBO(93, 34, 221, 1), textColor: Color.fromRGBO(223, 211, 248, 1)),
      appColors: const AppColors(primaryMuted: Color(0xFF7B60B8)),
      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromRGBO(126, 79, 227, 1),
      surfaceTint: Color(4291673599),
      onPrimary: Color.fromRGBO(255, 255, 255, 1),
      primaryContainer: Color.fromRGBO(43, 50, 59, 1),
      onPrimaryContainer: Color(4278190080),
      secondary: Color(4292991218),
      onSecondary: Color(4280754998),
      secondaryContainer: Color(4287925669),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4294955230),
      onTertiary: Color(4282194472),
      tertiaryContainer: Color.fromRGBO(158, 123, 234, 0.16),
      onTertiaryContainer: Color.fromRGBO(158, 123, 234, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4294923337),
      onErrorContainer: Color(4278190080),
      surface: Color(4279505688),
      onSurface: Colors.white,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4290097339),
      outlineVariant: Color.fromRGBO(65, 75, 88, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4293321193),
      inversePrimary: Color(4283187063),
      primaryFixed: Color(4293451519),
      onPrimaryFixed: Color(4279501629),
      primaryFixedDim: Color(4291673599),
      onPrimaryFixedVariant: Color(4282002788),
      secondaryFixed: Color(4293385976),
      onSecondaryFixed: Color(4279438880),
      secondaryFixedDim: Color(4291544028),
      onSecondaryFixedVariant: Color(4281873223),
      tertiaryFixed: Color(4294957540),
      onTertiaryFixed: Color(4280550932),
      tertiaryFixedDim: Color(4293834953),
      onTertiaryFixedVariant: Color(4283444025),
      surfaceDim: Color(4279505688),
      surfaceBright: Color(4282794826),
      surfaceContainerLowest: Color(4278716172),
      surfaceContainerLow: Color(4280163618),
      surfaceContainer: Color(4280887085),
      surfaceContainerHigh: Color(4281610808),
      surfaceContainerHighest: Color.fromRGBO(65, 75, 88, 1),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(
      darkScheme(),
      BadgeThemeData(backgroundColor: Color.fromRGBO(93, 34, 221, 1), textColor: Color.fromRGBO(223, 211, 248, 1)),
      appColors: const AppColors(primaryMuted: Color(0xFF7B60B8)),

      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color.fromRGBO(126, 79, 227, 1),
      surfaceTint: Color(4291673599),
      onPrimary: Color.fromRGBO(255, 255, 255, 1),
      primaryContainer: Color.fromRGBO(43, 50, 59, 1),
      onPrimaryContainer: Color(4279107636),
      secondary: Color(4294241791),
      onSecondary: Color(4278190080),
      secondaryContainer: Color(4291280856),
      onSecondaryContainer: Color.fromRGBO(138, 151, 168, 1),
      tertiary: Color(4294962160),
      onTertiary: Color(4278190080),
      tertiaryContainer: Color.fromRGBO(158, 123, 234, 0.16),
      onTertiaryContainer: Color.fromRGBO(158, 123, 234, 1),
      error: Color.fromRGBO(181, 52, 23, 1),
      onError: Color.fromRGBO(255, 255, 255, 1),
      errorContainer: Color(4294946468),
      onErrorContainer: Color(4280418305),
      surface: Color.fromRGBO(22, 25, 29, 1),
      onSurface: Colors.white,
      onSurfaceVariant: Color.fromRGBO(108, 125, 147, 1),
      outline: Color(4294242041),
      outlineVariant: Color.fromRGBO(65, 75, 88, 1),
      shadow: Color(4278190080),
      scrim: Color(4278190080),
      inverseSurface: Color(4293321193),
      inversePrimary: Color(4283187063),
      primaryFixed: Color(4293451519),
      onPrimaryFixed: Color(4278190080),
      primaryFixedDim: Color(4291673599),
      onPrimaryFixedVariant: Color(4279501629),
      secondaryFixed: Color(4293385976),
      onSecondaryFixed: Color(4278190080),
      secondaryFixedDim: Color(4291544028),
      onSecondaryFixedVariant: Color(4279438880),
      tertiaryFixed: Color(4294957540),
      onTertiaryFixed: Color(4278190080),
      tertiaryFixedDim: Color(4293834953),
      onTertiaryFixedVariant: Color(4280550932),
      surfaceDim: Color(4279505688),
      surfaceBright: Color(4283584341),
      surfaceContainerLowest: Color(4278190080),
      surfaceContainerLow: Color(4280295204),
      surfaceContainer: Color(4281478965),
      surfaceContainerHigh: Color(4282202689),
      surfaceContainerHighest: Color.fromRGBO(65, 75, 88, 1),
    );
  }

  ThemeData darkHighContrast() {
    return theme(
      darkScheme(),
      BadgeThemeData(backgroundColor: Color.fromRGBO(93, 34, 221, 1), textColor: Color.fromRGBO(223, 211, 248, 1)),
      appColors: const AppColors(primaryMuted: Color(0xFF7B60B8)),
      pillSegmentedButton: const PillSegmentedButtonThemeData(),
      pillChip: const PillChipThemeData(),
    );
  }

  ThemeData theme(
    ColorScheme colorScheme,
    BadgeThemeData badgeThemeData, {
    required AppColors appColors,
    PillChipThemeData? pillChip,
    PillSegmentedButtonThemeData? pillSegmentedButton,
  }) => ThemeData(
    extensions: [appColors, if (pillChip != null) pillChip, if (pillSegmentedButton != null) pillSegmentedButton],
    useMaterial3: true,
    badgeTheme: badgeThemeData.copyWith(
      textStyle: TextStyle(fontWeight: FontWeight.w500, fontSize: 12, color: badgeThemeData.textColor),
    ),
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: textTheme
        .apply(bodyColor: colorScheme.onSurface, displayColor: colorScheme.onSurface)
        .copyWith(labelLarge: textTheme.labelLarge!.copyWith(color: colorScheme.onSurface, height: 1.6))
        .copyWith(
          titleLarge: textTheme.titleLarge!.copyWith(
            fontSize: 16,
            fontWeight: FontWeight.w500,
            color: colorScheme.onSurface,
            height: 1.8,
          ),
          titleMedium: textTheme.titleMedium!.copyWith(
            fontSize: 14,
            fontWeight: FontWeight.w500,
            color: colorScheme.onSecondaryContainer,
            height: 1.6,
          ),
        ),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surface,
    // iOS needs CupertinoPageTransitionsBuilder to support the swipe-right-to-go-back gesture.
    // FadeForwardsPageTransitionsBuilder does not provide this gesture.
    pageTransitionsTheme: PageTransitionsTheme(
      builders: Map<TargetPlatform, PageTransitionsBuilder>.fromIterable(
        TargetPlatform.values,
        value: (platform) => platform == TargetPlatform.iOS
            ? const CupertinoPageTransitionsBuilder()
            : const FadeForwardsPageTransitionsBuilder(),
      ),
    ),
    segmentedButtonTheme: SegmentedButtonThemeData(
      style: ButtonStyle(
        backgroundColor: WidgetStateProperty.resolveWith((states) {
          if (states.contains(WidgetState.selected)) {
            return colorScheme.surfaceContainerHigh;
          }
          return colorScheme.primaryContainer;
        }),
        shape: WidgetStateProperty.all(RoundedRectangleBorder(borderRadius: BorderRadius.circular(8))),
        foregroundColor: WidgetStateProperty.all(colorScheme.onSurface),
        overlayColor: defaultTargetPlatform == TargetPlatform.iOS ? WidgetStateProperty.all(Colors.transparent) : null,
        splashFactory: defaultTargetPlatform == TargetPlatform.iOS ? NoSplash.splashFactory : null,
        textStyle: WidgetStateProperty.all(const TextStyle(fontSize: 13, fontWeight: FontWeight.w500)),
      ),
    ),
    listTileTheme: ListTileThemeData(
      titleTextStyle: TextStyle(color: colorScheme.onSurface, fontWeight: FontWeight.w500, fontSize: 16),
      subtitleTextStyle: TextStyle(color: colorScheme.onSecondaryContainer, fontWeight: FontWeight.w500, fontSize: 14),
      leadingAndTrailingTextStyle: TextStyle(
        color: colorScheme.onSecondaryContainer,
        fontWeight: FontWeight.w500,
        fontSize: 16,
      ),
    ),
  );

  List<ExtendedColor> get extendedColors => [];
}

class AppColors extends ThemeExtension<AppColors> {
  const AppColors({required this.primaryMuted});

  /// A muted/lighter variant of primary, for use as a subdued accent on primary surfaces
  final Color primaryMuted;

  @override
  AppColors copyWith({Color? primaryMuted}) {
    return AppColors(primaryMuted: primaryMuted ?? this.primaryMuted);
  }

  @override
  AppColors lerp(AppColors? other, double t) {
    if (other is! AppColors) return this;
    return AppColors(primaryMuted: Color.lerp(primaryMuted, other.primaryMuted, t)!);
  }
}

class ExtendedColor {
  final Color seed, value;
  final ColorFamily light;
  final ColorFamily lightHighContrast;
  final ColorFamily lightMediumContrast;
  final ColorFamily dark;
  final ColorFamily darkHighContrast;
  final ColorFamily darkMediumContrast;

  const ExtendedColor({
    required this.seed,
    required this.value,
    required this.light,
    required this.lightHighContrast,
    required this.lightMediumContrast,
    required this.dark,
    required this.darkHighContrast,
    required this.darkMediumContrast,
  });
}

class ColorFamily {
  const ColorFamily({
    required this.color,
    required this.onColor,
    required this.colorContainer,
    required this.onColorContainer,
  });

  final Color color;
  final Color onColor;
  final Color colorContainer;
  final Color onColorContainer;
}
