name: Flutter format
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/flutterfmt.yml'
      - '.github/workflows/flutterfmt.sh'
      - '**.dart'
jobs:

  gofmt:
    name: Run flutter format
    runs-on: ubuntu-latest
    steps:

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Check out code
        uses: actions/checkout@v3

      - name: Check formating
        run: dart format -l120 lib/ --set-exit-if-changed --suppress-analytics --output none