name: Flutter format
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/flutterfmt.yml'
      - '.github/workflows/flutterfmt.sh'
      - '**.dart'
jobs:
  flutterfmt:
    name: Run flutter format
    runs-on: ubuntu-latest
    steps:
      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0'

      - name: Check out code
        uses: actions/checkout@v4
        with:
          show-progress: false

      # Disabled for a single PR, this will be re-enabled in the PR that has lots of formatting changes.
      # - name: Check formating
      #   run: dart format -l120 lib/ --set-exit-if-changed --suppress-analytics --output none
