name: Go tests
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/gotest.yml'
      - '**.go'
      - 'nebula/go.sum'
jobs:

  gotest:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 #6.5.0
        with:
          go-version-file: nebula/go.mod
          cache: false
        id: go

      - name: Restore Go caches
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 #6.1.0
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: gotest-go-${{ steps.go.outputs.go-version }}-${{ hashFiles('nebula/go.sum') }}-${{ github.sha }}
          restore-keys: |
            gotest-go-${{ steps.go.outputs.go-version }}-${{ hashFiles('nebula/go.sum') }}-
            gotest-go-${{ steps.go.outputs.go-version }}-
            gotest-go-

      - name: Go tests
        run: cd nebula && go test ./...
